### ISSUE TITLE
initial admin/password to random secret

### ISSUE THREAD

**Issue by tekkisse** [sagikazarmark/helm-charts#108]
be good to be able to set the initial admin user and password (not password??).  The core product does not seem to do this - do you know if his is possible.

Your chart could then be extended to enable a secrets file t generate and hold the pasword/username

**Comment by sagikazarmark** [comment]
I assume you are talking about sftpgo, right?

If so, it's already possible to load initial data, including admin users.

In values, you need to set:

```yaml
env:
  SFTPGO_LOADDATA_FROM: "/etc/sftpgo/loaddata/data.json"
  SFTPGO_LOADDATA_MODE: "0"


volumes:
  - name: load-data
    secret:
      secretName: "${load_data}"

volumeMounts:
  - name: load-data
    mountPath: /etc/sftpgo/loaddata
```

Then you need to create a configmap/secret that you can mount as a file with the following (or similar) content:

```json
{
    "users": [
       // LIST OF INITIAL USERS
    ],
    "folders": [],
    "admins": [
        {
            "id": 1,
            "status": 1,
            "username": "admin",
            "password": "BCRYP_HASH",
            "email": "",
            "permissions": [
                "*"
            ],
            "filters": {}
        }
    ],
    "version": 8
}
```

Read the official configuration for more.
