### ISSUE TITLE
Configuration not working with chart

### ISSUE THREAD

**Issue by dmouha-xelians** [sagikazarmark/helm-charts#192]
Hello,

I used the helm and chart to install sftpgo on my kubernetes cluster. The installation is ok but it seems that the configuration is not taken into account.

In the **values.yaml** I have

```
config:
    common:
      upload_mode: 1
    defender:
      enabled: true
      ban_time: 60
      ban_time_increment: 50
    sftpd:
      bindings:
        port: 2022
      max_auth_retries: 3
      password_authentication: true
      enabled_ssh_commands: "*"
    telemetry:
      enable_profiler: false
```

This translate into a json in **/etc/sftpgo/sftpgo.json** 

```
{
	"common": {
		"upload_mode": 1
	},
	"defender": {
		"ban_time": 60,
		"ban_time_increment": 50,
		"enabled": true
	},
	"enabled_ssh_commands": "*",
	"sftpd": {
		"bindings": {
			"port": 2022
		},
		"max_auth_retries": 3,
		"password_authentication": true
	},
	"telemetry": {
		"enable_profiler": false
	}
}
```

But when I check the maintenance page, it seems that the configuration did not work for defender. It status is still disabled.
I tried to enforce the environment variable:  SFTPGO_CONFIG_FILE to the configuration file but still not working.
Can you please provide guidance on how to **make defender enabled and  enabled_ssh_commands to ***

Thanks
