### ISSUE TITLE
Better tusd configuration

### ISSUE THREAD

**Issue by sagikazarmark** [sagikazarmark/helm-charts#49]
Currently tusd can be configured directly via container args. Let's add a better config structure so that container args are not exposed.

Example:

```yaml
config:
  basePath:
  behindProxy:
  maxSize:
  timeout:
  uploadDir:
  verbose:

  tls:
    certPath:
    keyPath:
    mode:

  hooks:
    enabled: []
    stopCode:

    file:
      path:
    http:
      endpoint:
      backoff:
      forwardHeaders:
      retry:
    grpc:
      endpoint:
      backoff:
      retry:
    plugin:
      path:

  storage:
    gcs:
      bucket:
      objectPrefix:
    s3:
      bucket:
      objectPrefix:
      disableContentHashes:
      disableSsl:
      endpoint:
      partSize:
      transferAcceleration:

```
